version: '3'

services:
  nginx:
    restart: always
    build:
      context: ./nginx
    container_name: nginx
    networks:
      - node-network
    ports:
      - '8080:80'
    depends_on:
      - app

  app:
    build:
      context: ./node
    container_name: app
    networks:
      - node-network
    volumes:
      - ./node:/usr/src/app
    tty: true
    depends_on:
      - db

  db:
    image: mysql:5.7
    command: --init-file /data/application/init.sql
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./db_mysql:/var/lib/mysql
      - ./data/init.sql:/data/application/init.sql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network

networks:
  node-network:
    driver: bridge
